### ISSUE TITLE
Doesn't reload dependency-affected classes

### ISSUE THREAD

**Issue by alexandergunnarson** [ztellman/virgil#1]
First of all, I just want to thank you for your work on `virgil`! It's been really useful for a recent project of mine. It performs admirably as advertised — it does indeed auto-reload all the .java files in :java-source-paths, which is an extremely useful feature and has saved me quite a lot of time and sighing while waiting for the compiler.

However, that said, it doesn't reload dependency-affected classes. By that I mean that if class A imports or refers to in some way class B, and I make changes to class B's .java file, then B will reload/auto-compile, but A will not recognize that anything has changed (e.g. updated B code will not be called from  A). In the description for `virgil`, you say that " all the namespaces that rely on those files will be reloaded", but for some reason this is not happening — at least not for me. Am I missing something?

Thanks for listening. I'm a big fan of your work with e.g. `primitive-math` and `proteus` (yes, I use `proteus` in production, if you can believe it haha).

**Comment by ztellman** [comment]
I've seen this same problem, but as far as I can tell, fixing it requires
parsing all the other class files to create a dependency graph. If you can
think of a less onerous way to accomplish this, I'd be very happy to hear jt

**Comment by RadicalZephyr** [comment]
Couldn't you also just recompile every Java file in the project whenever one changes?  That would probably make the watch code less complicated, and achieve the desired effect.

I suppose the most undesirable part is that then more clojure namespaces would potentially be reloaded than is strictly necessary...

**Comment by ztellman** [comment]
I think this also requires some care w.r.t. the order in which files are compiled, even if you do all of them.  I need to come up with some good test cases to understand all the interactions, though.  I agree that is at least a decent initial step.

**Comment by ztellman** [comment]
In 0.1.2, I've made it so that we just reload everything, since that's the easiest solution to this problem.  I'll look at how to do this a little more subtly in the future.

**Comment by ztellman** [comment]
Hmm, there are still some subtleties here in terms of class load order.  I'm going to have to cut a new release once I figure it out.

**Comment by ztellman** [comment]
Okay, this should be super-for-real fixed in 0.1.3.  Let me know if you find any issues.
