### ISSUE TITLE
cider-nrepl 0.16.0-SNAPSHOT causes "an exception has occured in the compiler"/IllegalAccessError

### ISSUE THREAD

**Issue by schmir** [ztellman/virgil#18]
When using virgil with cider-nrepl 0.16.0-SNAPSHOT, the java compiler is not able to report errors in source files. Instead it reports:
```
An exception has occurred in the compiler (1.8.0_152). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.

IllegalAccessError tried to access class com.sun.tools.javac.util.Log$2 from class com.sun.tools.javac.util.Log  com.sun.tools.javac.util.Log.getWriter (Log.java:372)
```

See https://github.com/schmir/cider-vs-javac for a repository demonstrating the error and the issue in cider-nrepl's repository: https://github.com/clojure-emacs/cider-nrepl/issues/463

At the moment I'm not sure how to fix the problem, though there is a workaround and a short note in the readme may save the next person from spending way too much time on this issue.

The workaround is to add :injections in project.clj:

```
   :injections [(require 'cider.nrepl.middleware.util.java)]
```

**Comment by alexander-yakushev** [comment]
Please, see further description of the problem and possible solution here: https://github.com/clojure-emacs/cider-nrepl/issues/463#issuecomment-369913283.

@ztellman, if the `(get-java-compiler)` workaround is OK with you, I will submit a PR.

**Comment by schmir** [comment]
I can confirm that this workaround fixes the issue for me. I recommend including it in virgil.

The :injections workaround mentioned above doesn't work anymore since the cider people moved some stuff around.

**Comment by ztellman** [comment]
I’ll happily accept a PR that fixes this issue.
