### ISSUE TITLE
Static method changes handled?

### ISSUE THREAD

**Issue by brentvukmer** [ztellman/virgil#29]
Thanks for making Virgil available, @ztellman! 

I created a Java class in my Clojure project to try out Virgil via Leiningen.  Instance method changes triggered a recompile/reload, but not (as far as I could tell) static method changes.  Is this a known issue?

**Comment by ztellman** [comment]
Is the class containing the static method explicitly imported?

**Comment by brentvukmer** [comment]
Looks like I was wrong:

- opened a fresh REPL (in Cursive)
- referenced the class static method (and then imported when prompted)
- changed the static method
- saw the class get recompiled

Sorry to bug you!
