### ISSUE TITLE
PR for separating compilation from watching code

### ISSUE THREAD

**Issue by RadicalZephyr** [ztellman/virgil#4]
Hey, I've been playing with doing something similar to this in Boot, and gotten things working to a large degree just by copy-paste-modify.

Now however I'd like to release an actual library with a new boot task and I thought perhaps I'd contribute back to virgil a bit and use it as a dependency.

So. My question is, if I were to submit a PR that separates out the java compiling code from the code for file-watching and reloading namespaces, would that be likely to get merged?

Also, thanks for your work on virgil!

**Comment by ztellman** [comment]
Sure, that sounds good to me.
